added sigbovik material

diff --git a/scripts/choice b/scripts/choice
--- a/scripts/choice
+++ b/scripts/choice
@@ -1,9 +1,28 @@
 #!/bin/bash
 
-stdin=`cat`
+# We need to store the contents of stdin explicitly to a file.  When we call one of our candidate parsers, it will consume some of the input form stdin. We need to restore that input before calling the next parser.
+stdin=$(tempfile)
+cat >"$stdin"
 
+# If stdin is empty, then we're done with recursion; parsing succeeded
+if [ ! -s "$stdin" ]; then
+    exit 0
+fi
+
+# For similar reasons, we'll need to store the output of our parsers.
+stdout=$(tempfile)
+stderr=$(tempfile)
+
+# For each parser passed in as a command line arg
 for cmd in "$@"; do
-    #echo "cmd=[$cmd]" >&2
-    stdout=$(eval "echo \"$stdin\" | $cmd") && echo -n "$stdout" && exit 0
+
+    # Run the parser; if it succeeds, then pass on its results
+    if $(eval "$cmd" <"$stdin" 1>"$stdout" 2>"$stderr") ; then
+        cat "$stderr" >&2
+        cat "$stdout"
+        exit 0
+    fi
 done
+
+# All parsers failed, so we failed
 exit 1
diff --git a/scripts/match b/scripts/match
--- a/scripts/match
+++ b/scripts/match
@@ -1,19 +1,30 @@
 #!/bin/bash
 
-if [ -z "$1" ] || [ ! -z "$2" ]; then 
+# check for the correct number of arguments
+if [ -z "$1" ] || [ ! -z "$2" ]; then
     echo "match requires exactly one argument"
     exit 255
 fi
 
-IFS=
+# When reading from stdin, the shell ignores the contents of the IFS variable. By default, this is set to whitespace. In order to be able to read whitespace, we must set IFS to nothing.
+IFS=''
+
+# read in exactly as some characters as are in the first command line argument
 read -rn "${#1}" in
 
-#echo "in=[$in]" >&2
-#echo "stdout=[$stdout]" >&2
-
+# if we parse correctly
 if [ "$1" = "$in" ]; then
+    # print the parsed string to stderr
     echo -n "$in" 1>&2
+
+    # forward the unparsed contents of stdin
     cat
+
+    # signal that parsing succeeded
     exit 0
+
+else
+    # parsing failed
+    exit 1
 fi
-exit 1
+
